apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  #Has to be same name of the service
  name: chuck-norris-app
spec:
  defaultSubset: v1
  subsets:
    v1:
      filter: 'Service.Meta.version == v1'
      onlyPassing: true
    v2:
      filter: 'Service.Meta.version == v2'
      onlyPassing: true
